=== alaksej/TheatreBookingSystem/TheatreBookingSystem/App_Data/Repertoire.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
     targetNamespace="http://yankou.com/LabProject/repertoire"
     xmlns:rep="http://yankou.com/LabProject/repertoire">
  <xs:element name="repertoire">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="play" type="rep:Play" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:complexType name="Play">
    <xs:sequence>
      <xs:element name="name" type="xs:string"/>
      <xs:element name="dates" type="rep:Dates"/>
    </xs:sequence>
		<xs:attribute name="id" type="xs:integer" use ="required"/>
		<xs:attribute name="author" type="xs:string" use ="required"/>
    <xs:attribute name="genre" type="xs:string" use ="required"/>
  </xs:complexType>
  <xs:complexType name="Dates">
    <xs:sequence>
      <xs:element name="date" type="rep:Date" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
	<xs:complexType name="Date">
		<xs:simpleContent>
			<xs:extension base="xs:date">
				<xs:attribute name="id" type="xs:integer" use="required" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
</xs:schema>

=== alaksej/TheatreBookingSystem/TheatreBookingSystem/App_Data/Repertoire.xml
<?xml version="1.0" encoding="utf-8" ?>
<rep:repertoire xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xsi:schemaLocation="http://yankou.com/LabProject/repertoire Repertoire.xsd"
                xmlns:rep="http://yankou.com/LabProject/repertoire">
  <play id="1" author ="Aliaksei Dudarau" genre="Mystical legend about love">
    <name>Black lady of Niasvizh</name>
    <dates>
      <date id="1">2016-10-05</date>
      <date id="2">2016-11-16</date>
    </dates>
  </play>
  <play id="2" author="Yanka Kupala" genre="Comedy">
    <name>Paulinka</name>
    <dates>
      <date id="3">2016-10-02</date>
      <date id="4">2016-12-10</date>
      <date id="5">2016-07-27</date>
    </dates>
  </play>
  <play id="3" author="Ales Adamovich" genre="Drama">
    <name>Not mine</name>
    <dates>
      <date id="6">2016-12-03</date>
      <date id="7">2016-07-17</date>
      <date id="8">2016-11-22</date>
    </dates>
  </play>
  <play id="4" author ="Aliaksei Dudarau" genre="Drama">
    <name>Prince Vitaut</name>
    <dates>
      <date id="9">2016-10-07</date>
      <date id="10">2016-07-18</date>
    </dates>
  </play>
</rep:repertoire>
